### ISSUE TITLE
Question: firmware

### ISSUE THREAD

**Issue by Omirax** [mercenaruss/zigbee-stick-v4#1]
Excellent work. Thank you!
However, the wiki does not answer the question of what firmware to flash?

**Comment by mercenaruss** [comment]
> Excellent work. Thank you!
> However, the wiki does not answer the question of what firmware to flash?

You can use Koen firmware: CC1352P_2_20200925.zip 
Now I work on firmwar to enable integrated PA for 20 dbm.
In mean time stick is still working with Koen firmware.
Will update,when custom firmware is done.

**Comment by mercenaruss** [comment]
Koen Firmware
