### ISSUE TITLE
ZigStar community forum for general discussions (that are not "issues" by deffinition)

### ISSUE THREAD

**Issue by Hedda** [mercenaruss/zigbee-stick-v4#10]
@mercenaruss continuing the request/suggestion for a general ZigStar community discussion forum from https://github.com/home-assistant/home-assistant.io/pull/20320

Recommend enable GitHub Discussions https://docs.github.com/en/discussions to allow "ZigStar discussions" under its own community repo like https://github.com/zigstar/zigstar_community_resources/discussions or alternatively in one of your other exisitng GiHub repos and use that "discussion section" to use as a general ZigStar communication forum. 

PS: Yes I know that you have a dedicated forum thread in the HA community forum but I  think it would be best to have your own "discussion" space here on where people can create separate threads for different topics so it is not all in one thread. Plus there will sooner of later be people from other communities than HA that will use ZigStar products if you market them as usable with Zigbee2MQTT, Home Assistant, and iOBroker (as well as later maybe also OpenHAB once they add support for TI Z-Stack 3 in their Zigbee Binding).

**Comment by Hedda** [comment]
See these example of these how other these communities uses this GitHub Discussions feature, some with dedicated repos for it:

https://github.com/home-assistant/architecture/discussions/

https://github.com/esphome/esphome/discussions

https://github.com/Koenkk/zigbee2mqtt/discussions/

https://github.com/arendst/Tasmota/discussions

https://github.com/zigpy/zigpy/discussions

**Comment by mercenaruss** [comment]
@Hedda Discussions enabled. Thanks
