### ISSUE TITLE
Request for easyEDA project files

### ISSUE THREAD

**Issue by irakhlin** [mercenaruss/zigbee-stick-v4#12]
Hello,
First off just wanted to thank you for the project, recently received a zigstar4 that is currently being used a router and I am loving the range. I was hoping it would be possible for you to share the easyeda project files used to generate the gerber files. I am hoping to add a few components, specifically a temperature/humidity sensor and potentially a light sensor. I have no plans to mass produce any result  as it would be simply a hobby project. The easyEDA project files would give me some starting points in designing the PCB. 

Please let me know if this is possible.

**Comment by mercenaruss** [comment]
Unfortunately i cant provide this.
But i'm very open for improvements,if you have any in mind you can drop me an email on support@zig-star.com
