### ISSUE TITLE
How to flash Zigstar Shield using python

### ISSUE THREAD

**Issue by hacor** [mercenaruss/zigbee-stick-v4#14]
Hello!

Forgive me this newbie question, but I was wondering if you could guide me in how to flash the Z2M firmware onto my Zigstar shield. I will be using the [z-stack firmware](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) as suggested on the Zigstar Shield page.

I was wondering on how to enable the programming mode. Because with the USB stick it is clear you need to push the BSL button when plugging it in, but not sure how to get there with the shield.
I was hoping to be able to program the device using the python `cc2538-bsl.py` script from the raspberry pi itself without the need of an external programmer. Perhaps I was to optimistic :-)

Warm regards

Hacor

**Comment by mercenaruss** [comment]
@hacor Hi,this is possible to do. A little work arounf is required. Give some time to check and revert.

**Comment by mercenaruss** [comment]
I dig in this:
1. Shield can be programmed using cc2538-bsl.py
2. You need to press RST and BSL simultaneously and release RST in the same time holding BSL then runn script for update.

You are done!

**Comment by hacor** [comment]
@mercenaruss Fantastic! Thank you.
Closing this issue
