### ISSUE TITLE
Router problem

### ISSUE THREAD

**Issue by r312645** [mercenaruss/zigbee-stick-v4#2]
I flashed [this router firmware.](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin) 
It works well, but how do I re-pair to other coordinator?
I pressed the reset button but nothing happened.

**Comment by mercenaruss** [comment]
Please flash next firmware: https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_router_20210128.zip 

Before flash, let coordinator be in pairing mode,so when router is flashed he will search automatically to pair.

**Comment by r312645** [comment]
Thanks for reply.
Does that mean I can only re-flash the firmware to re-pair ?
Can I reset router like the picture below？

![Screenshot_2021-02-04-22-40-56-55](https://user-images.githubusercontent.com/58178973/106909150-f4566980-673a-11eb-99ef-80e12fa65067.jpg)

**Comment by r312645** [comment]
Thanks for reply.
Does that mean I can only re-flash the firmware to re-pair ?
Can I reset router like the picture below？


Radu <notifications@github.com> 於 2021年2月4日 週四 22:33 寫道：

**Comment by mercenaruss** [comment]
you can do it,you have 2 button on PCB,try them,i didnt install this firmware,i need to test.

**Comment by r312645** [comment]
I found that the bsl button works, thank you.  I have not installed the bsl
button because I do not have 100 ohm.  Now I use 1k ohm on the bsl button,
will this cause any problems?

Radu <notifications@github.com> 於 2021年2月4日 週四 23:29 寫道：

**Comment by mercenaruss** [comment]
> se any problems?

if button is its working then no problem.
Thank you for update.
