### ISSUE TITLE
improvemt suggestion - expose serial connection to border connector

### ISSUE THREAD

**Issue by klassisch** [mercenaruss/zigbee-stick-v4#3]
Thanks a lot for your great work developing this board and presenting it here.
I have a suggestion for an improvement in future releases or similar projects:
The USB port is not always the best solution for everyday operation. 
Many automation systems are running on a server or computer not beeing located at the best location regarding the needs of RF wave propagation.
So, an ethernet interface is a good supplement.
This can be done using a commercially available converter such as USR-TCP232-T2 or similar.
I hand-modified your module to attach such an add-on.
Unfortunately I had to cut a trace and to make some ugly solder mods.
In future versions it would be highly appreciated if you could support such alternative signal paths by exosing the serial signals to the (extented) border connector. It could be as
* tap the connection between cc2652P module Txd to CH340 RxD and connet it to an additional connector pin
* connect the cc2652P module RxD to an additional connector pin  
* connect the CH340 TxD to an additional connector pir
* connect the cc2652 RxD to the CH340 TxD by a removable link such as a jumper or a resistor which could be removed
* if possible and space left, connect the +5V to an additional connector pin

I modified your board by cuttin and adding some wires. 

![grafik](https://user-images.githubusercontent.com/35134055/112715096-ba097d00-8ede-11eb-82af-7722a7140119.png)

It looks ugly like this but it works.
![grafik](https://user-images.githubusercontent.com/35134055/112715067-6f880080-8ede-11eb-9a31-5b7378fde999.png)

![grafik](https://user-images.githubusercontent.com/35134055/112715109-d5748800-8ede-11eb-90b2-4003376454ba.png)

I have more images and a description in the ioBroker forum (German language) https://forum.iobroker.net/post/601380 .

**Comment by mercenaruss** [comment]
@klassisch Hello and thank you for kind suggestion.
We can discuss this in Telegram,so we can bring to life a new device.
Please contact me: https://t.me/mercenaruss

**Comment by mercenaruss** [comment]
Following our discussion please be notified,that your wished was taken in consideration.
Work is ongoing.
