### ISSUE TITLE
Low Range / Link Quality

### ISSUE THREAD

**Issue by lg-eng** [mercenaruss/zigbee-stick-v4#4]
Hi there, thanks for the nice design! I bought one of them from ebay. It is working as a coordinator but unfortunately the range is very poor. max ~2m line of sight. Do you have any suggestions where to start tweaking to improve the range? Could a software update help?

Thanks!

**Comment by lg-eng** [comment]
Hi again, I did some research and it appears there is a resistor missing going to the onboard antenna. I guess this is necessary to disable the onboard antenna? But how is the board connected with the external antenna? Shouldn't be there a jumper or something? 
![image](https://user-images.githubusercontent.com/72553092/118033409-1595aa00-b369-11eb-9aab-de996b3237ba.png)

**Comment by lg-eng** [comment]
Problem solved! Jumper in green. LQI to an OSRAM switch @ 40cm is 132 outgoing and 142 incoming. Second OSRAM Switch @ 5m and two walls (20cm bricks) 18/50. Anyone with some reference measurements? 
![image](https://user-images.githubusercontent.com/72553092/118036739-3bbd4900-b36d-11eb-97d1-dac86d14c0cd.png)

**Comment by lg-eng** [comment]
Thanks again for the board and of course for sharing!

**Comment by mercenaruss** [comment]
Hello @lg-eng ,sorry for late answer. You are right resistor supposed to be repositioned  in order to use external antenna,just solder the resistor to match external antenna.
Will add this description on github.

**Comment by lg-eng** [comment]
Ah now worries I'm glad you answered! So there should be a resistor? I just soldered a wire as a jumper because the resistor was missing entirely. Do you have, by any chance, the value of the resistor?

**Comment by mercenaruss** [comment]
@lg-eng Please follow the picture.
Just make a swap according to the picture.
![S20210515_0005](https://user-images.githubusercontent.com/5508130/118377174-de6f0500-b5c3-11eb-9c55-b08e57cb74da.jpg)

**Comment by lg-eng** [comment]
Thanks for the picture, unfortunately I do not have this resistor any more. I have to replace it. Could you share the value of the resistor?

**Comment by mercenaruss** [comment]
> Thanks for the picture, unfortunately I do not have this resistor any more. I have to replace it. Could you share the value of the resistor?

Sorry,is no a resistor. I cant identify.
