### ISSUE TITLE
Question: can you post the CPL file?

### ISSUE THREAD

**Issue by gabr777** [mercenaruss/zigbee-stick-v4#6]
Very nice project, thanks for sharing. 
I'm looking at the 4.0 version of CH340E.
Could you post the CPL file that is needed for the SMT assembly through jlcpcb?

**Comment by mercenaruss** [comment]
Hello, yes, i will post it soon,will be available on zig-star.com in couple of days.

**Comment by lifeandfate1** [comment]
Hey just wanted to check in with the CPL file. I can't find it on zig-star.com

**Comment by mercenaruss** [comment]
@gabr777 and @lifeandfate1 for which version you need CPL file? CH340E or CH340C ?

**Comment by mercenaruss** [comment]
@gabr777 and @lifeandfate1 ,sorry for question,but for what is required CPL file in your case? Mass production?

**Comment by lifeandfate1** [comment]
I was just wanting one and to get jlcpcb to make one for me.

**Comment by mercenaruss** [comment]
@lifeandfate1 minimum quantity for JLPCB is 2 SMT and 5 PCB.
Anyways RF-Star Module is not possible to do on JLPCB,you need to buy separately.
You can find all information on [website](zig-star.com)

**Comment by randarth** [comment]
Hi, first of all - thanks for great work and for sharing it!
I would also like to buy some preassembled sticks from jlcpcb. Not for mass production, but I'll need at least 4 pcs for friends and family who I managed to switch from various tuyas and ewelinks to Home Assistant. Right now we're using CC2531 sticks and ZHA and I want to migrate all of us to Zigbee2MQTT with better zigbee coordinators.
On Zigstar project website you wrote that CH340E version is "JLPBC SMT Assembly available", but looks like it's mandatory to have a file with SMD placement.
I know that they won't solder main RF-STAR module, but I think I'll manage that on my own.
Can you add this cpl file to github?

**Comment by mercenaruss** [comment]
Hello everyone, @randarth @lifeandfate1 @gabr777 Pick and Place file now available in repository,please use new gerbers for CH340E version,they will match with Pick and Place.
