### ISSUE TITLE
"ZigStar Stick" name change discussion

### ISSUE THREAD

**Issue by Hedda** [mercenaruss/zigbee-stick-v4#9]
@mercenaruss to continue the "ZigStar Stick" name change discussion from https://github.com/home-assistant/home-assistant.io/pull/20320

I changed "ZigStar Stick v4" to just "ZigStar Stick" in the initial https://github.com/home-assistant/home-assistant.io/pull/20320 pull request for ZHA docs but otherwise, I think would be best to leave 'as is' for now and then do new PR just changing that small detail in the ZHA docs after you have updated all your sites to use the new name chosen because right now can see that they all still old "ZigStar Stick v4" name. 

Thus it will certainly be more confusing to change the name in ZHA docs first when you have not already changed it upstream. So be sure to change the name on all sites upstream first:

https://zig-star.com/projects/zigbee-stick-v4/

https://www.tindie.com/products/zigstar/zigstar-stick-v4/

https://github.com/mercenaruss/zigbee-stick-v4

Also remember that users have the option to reflash these sticks with Zigbee Router firmware and use them as Zigbee routers instead Zigbee coordinators. Thus personally I think you should leave the name as "ZigStar Stick" or use other similar general suffix (like ex. "ZigStar USB Stick", "ZigStar USB Dongle", or "ZigStar USB Adapter" which all work well as generic suffixes in product name).

**Comment by Hedda** [comment]
Personally, I think it would be a bad idea use "coordinator" as a suffix in the product name because generally, people out there new to the workings of Zigbee will not know what a "coordinator" is. I think that is why commercial coordinators usually are more likely to use product suffixes as "USB Stick", "USB Dongle", or "USB Adapter", because it then clearly tells in the product name what the product is. It uses "USB" which most people know what it is and it is a "stick"/"dongle"/"adapter" which also people are familiar with because of USB memory sticks and USB WiFi dongles/adapters.

**Comment by mercenaruss** [comment]
@Hedda like ussualy you have a good point in all this matters:
Personaly i prefer then to change the PR from: ZigStar Stick (CC2652 + CH340B variant) to ZigStar Stick or ZigStar Stick v4.

Can you do this? Is not late to change your PR? https://github.com/home-assistant/home-assistant.io/pull/20320

**Comment by mercenaruss** [comment]
@Hedda i just checked https://github.com/home-assistant/home-assistant.io/pull/20320 , name is not changed, i think we should keep it like is said in previous comment:
> Personaly i prefer then to change the PR from: ZigStar Stick (CC2652 + CH340B variant) to ZigStar Stick or ZigStar Stick v4.

**Comment by Hedda** [comment]
> @Hedda like ussualy you have a good point in all this matters: Personaly i prefer then to change the PR from: ZigStar Stick (CC2652 + CH340B variant) to ZigStar Stick or ZigStar Stick v4.
> 
> Can you do this? Is not late to change your PR? [home-assistant/home-assistant.io#20320](https://github.com/home-assistant/home-assistant.io/pull/20320)

Yes done here:

https://github.com/home-assistant/home-assistant.io/pull/20320/commits/d1b098bda19e234d4db0c8233ab1a1b4e766b764

https://github.com/home-assistant/home-assistant.io/blob/d1b098bda19e234d4db0c8233ab1a1b4e766b764/source/_integrations/zha.markdown

If the PR is merged 'as is' now then will look like this i ZHA docs:

| Device | Discovery Method | Identifier |
| -------| ---------------- | ---------- |
| [ConBee II](https://phoscon.de/en/conbee2) | USB | 1CF1:0030 |
| [Nortek HUSBZB-1](https://www.nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/) | USB | 10C4:8A2A |
| [slae.sh CC2652RB development stick](https://slae.sh/projects/cc2652/) | USB | 10C4:EA60 |
| [ZigStar Stick (CC2652 + CH340B variant)](https://zig-star.com/projects/zigbee-stick-v4/) | USB | 1A86:7523 |
| [Tube’s EFR32 Pro Ethernet/Serial Coordinator](https://www.tubeszb.com/) | USB| 10C4:EA60 |
| [Tube's CC2652P2 USB-powered Zigbee to Ethernet Serial Coordinator)](https://www.tubeszb.com/) | Zeroconf | tube_zb_gw_cc2652p2.local. |
| [Tube's CC2652P2 PoE-powered Zigbee to Ethernet Serial Coordinator)](https://www.tubeszb.com/) | Zeroconf | tube_zb_gw_cc2652p2_poe.local. |
| [Tube's EFR32 Based Zigbee to Ethernet Serial Coordinator)](https://www.tubeszb.com/) | Zeroconf | tube_zb_gw_efr32.local. |

**Comment by Hedda** [comment]
Just trying to think like a marketing person when naming a product to sound both self-explanatory and not intimidating.

"dongle", "stick", and "adapter" are all good, however, I think it is also smart to include "USB" as well to explain the type of device.

"ZigStar CC2652P USB Stick" might be an even better name as it is more descriptive and covers future sticks with other chips.

Say you decide to also release an EFR32MG21 stick as an option then that could be called "ZigStar EFR32MG21 USB Stick".

And a CC1352P stick would then get the name "ZigStar CC1352P USB Stick".

That way you would not paint yourself in a corner with a product name that is not future-proof.

At least it will get confusing and cluttered in lists if have a version/revision in the name or new adapter use different chips:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md

**Comment by mercenaruss** [comment]
@Hedda we understood wrong each other.
I mean to change like this, from:
[ZigStar Stick (CC2652 + CH340B variant)](https://zig-star.com/projects/zigbee-stick-v4/) | USB | 1A86:7523 |
 to:
[ZigStar USB Stick v4](https://zig-star.com/projects/zigbee-stick-v4/) | USB | 1A86:7523 |
or
[ZigStar USB Stick](https://zig-star.com/projects/zigbee-stick-v4/) | USB | 1A86:7523 |

It's kind of late, PR is merged already.
Will change this on next PR for zeroconf.
Anyway thank you very much for assistance.
